[package]
name = "rszcash"
version = "0.1.0"
authors = ["Sean Bowe <ewillbefull@gmail.com>"]

[lib]
name = "rszcash"
path = "src/rszcash.rs"
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.21"
